import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:4200/login');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('usuario@ejemplo.com');
  await page.getByRole('textbox', { name: 'Contraseña' }).click();
  await page.getByRole('textbox', { name: 'Contraseña' }).fill('miclave123');
  await page.getByRole('button', { name: 'Iniciar sesión' }).click();
  await page.getByRole('button', { name: 'Ir a Zonas' }).click();
  await page.getByRole('button', { name: 'Crear Zona' }).click();
  await page.getByRole('textbox', { name: 'Nombre de la Zona' }).click();
  await page.getByRole('textbox', { name: 'Nombre de la Zona' }).fill('5');
  await page.getByRole('spinbutton', { name: 'Latitud' }).click();
  await page.getByRole('spinbutton', { name: 'Latitud' }).fill('5');
  await page.getByRole('spinbutton', { name: 'Longitud' }).click();
  await page.getByRole('spinbutton', { name: 'Longitud' }).fill('5');
  await page.getByRole('spinbutton', { name: 'Radio (Km)' }).click();
  await page.getByRole('spinbutton', { name: 'Longitud' }).fill('55');
  await page.getByRole('spinbutton', { name: 'Radio (Km)' }).click();
  await page.getByRole('spinbutton', { name: 'Radio (Km)' }).fill('5');
  await page.getByRole('button', { name: 'Crear zona' }).click();
  await page.getByRole('button', { name: 'Listar Zona' }).click();
  await page.getByRole('button', { name: 'Siguiente >' }).click();
  await page.getByRole('button', { name: '< Anterior' }).click();
  await page.getByRole('button').nth(1).click();
  await page.locator('input[name="radius"]').click();
  await page.locator('input[name="radius"]').fill('5');
  await page.getByRole('button', { name: 'Guardar' }).click();
  await page.getByRole('button').first().click();
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('button', { name: 'Ir a Deliveries' }).click();
  await page.getByRole('button', { name: 'Crear repartidor' }).click();
  await page.getByRole('textbox', { name: 'Person ID' }).click();
  await page.getByRole('textbox', { name: 'Person ID' }).fill('5');
  await page.getByRole('spinbutton', { name: 'Radio (km)' }).click();
  await page.getByRole('spinbutton', { name: 'Radio (km)' }).fill('5');
  await page.getByRole('spinbutton', { name: 'Latitud' }).click();
  await page.getByRole('spinbutton', { name: 'Latitud' }).fill('5');
  await page.getByRole('spinbutton', { name: 'Longitud' }).click();
  await page.getByRole('spinbutton', { name: 'Longitud' }).fill('5');
  await page.getByRole('button', { name: 'Crear Repartidor' }).click();
  await page.getByRole('button', { name: 'Listar Repartidores' }).click();
  await page.getByRole('link', { name: 'Siguiente >' }).click();
  await page.getByRole('link', { name: '< Anterior' }).click();
  await page.getByRole('button').nth(1).click();
  await page.getByText('Asignar Zonas').click();
  await page.getByText('hola').first().click();
  await page.getByRole('button', { name: 'Guardar' }).click();
  await page.getByRole('button').nth(1).click();
  await page.getByLabel('Estado:').selectOption('available');
  await page.getByRole('button', { name: 'Guardar' }).click();
  await page.getByRole('button').first().click();
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('button', { name: 'Cerrar sesión' }).click();
});